# Generated by Django 3.2.7 on 2021-10-14 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Abonnement', '0002_alter_myuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriber', to=settings.AUTH_USER_MODEL),
        ),
    ]
