# Generated by Django 3.2.7 on 2021-10-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Abonnement', '0004_alter_abonnement_subdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonnement',
            name='subdate',
            field=models.DateField(auto_now_add=True, verbose_name='Date de subscription'),
        ),
    ]
